apiVersion: v3.2.0 # Standard version
kind: DataContract

# What's this data contract about?
id: 12345678-fakeid-12345678
name: None
version: 1.0.0
status: draft

description: 
  purpose: testing
  limitations: limitless
  usage: infinite


schema:
  - name: sleep_efficiency
    properties:
      - name: ID
        logicalType: integer
        unique: true

      - name: Age
        logicalType: integer
        logicalTypeOptions:
          exclusiveMinimum: 17

      - name: Gender
        logicalType: string
        enum:
          - value: Female
          - value: Male

      - name: Bedtime
        logicalType: timestamp
      
      - name: Wakeup time
        logicalType: timestamp
      
      - name: Sleep duration
        logicalType: number
      
      - name: Sleep efficiency
        logicalType: number
      
      - name: REM sleep percentage
        logicalType: integer
      
      - name: Deep sleep percentage
        logicalType: integer

      - name: Light sleep percentage
        logicalType: integer
      
      - name: Awakenings
        logicalType: integer
      
      - name: Caffeine consumption
        logicalType: number

      - name: Alcohol consumption
        logicalType: number

      - name: Smoking status
        logicalType: boolean
        enum:
          - value: Yes
          - value: No
      
      - name: Exercise frequency
        logicalType: boolean